language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip

install:
  - pip install pylint

script:
  - find . -name \*.py -exec pylint -r yes {} \;
